[package]
name = "db-mover"
description = "Tool to move data between databases"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
rusqlite = { version = "0.32.1", features = ["column_decltype", "bundled", "time"] }
postgres = "0.19.9"
indicatif = "0.17.11"
console = "0.15.11"

[dev-dependencies]
criterion = "0.5.1"
fake = "3.1.0"
rand = "0.9.0"
tempfile = "3.15.0"

[[bench]]
name = "sqlite_to_sqlite"
harness = false

[lints.clippy]
needless_return = "allow"
