[package]
name = "db-mover"
description = "Tool to move data between databases"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
async-channel = "2.3.1"
clap = { version = "4.5.23", features = ["derive"] }
rusqlite = { version = "0.32.1", features = ["column_decltype"] }
