[package]
name = "gen-bench-data"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.32.1", features = ["column_decltype"] }
fake = "3.1.0"
clap = { version = "4.5.23", features = ["derive"] }
